
[app]
name = "mabo_sup"
version = "0.0.1"
conf = "default"

[etcd]
URL = "http://localhost:8080/v2/keys"

[default]
redis_host = "localhost"
redis_port = "6379"
redis_db = 0
app_list = ["app1","app2"]

threshhold = 10
retry = 3
mail_to = ["mes@mabotech.com"]