# mabo-radar


ALL: ;

build:
	pyinstaller --icon=favicon.ico mabo_sup/checker.py 
    
build1:
	pyinstaller --onefile mabo_sup/checker.py 
    
mon:
	nodemon --exec "c:/python27/python.exe" mabo_sup/server.py


.PHONY: build